#!/bin/bash

if [ $(id -u) != 0 ]; then
   echo "Installing requires root-- please enter your password!"
   sudo "$0" || echo Sudo privileges couldn't be elevated, exiting!
   exit
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
        sudo sh -c "cd /boot/efi/EFI/refind/themes; echo "include themes/refind-jbm/theme.conf" >> /boot/efi/EFI/refind/refind.conf"
        sudo mkdir /boot/efi/EFI/refind/themes/
        sudo mkdir /boot/efi/EFI/refind/themes/refind-jbm
        sudo wget https://github.com/jbmagination/refind-jbm/releases/download/1.0.0/refind-jbm.zip --directory-prefix=/boot/efi/EFI/refind/themes/
        sudo unzip /boot/efi/EFI/refind/themes/refind-jbm.zip
elif [[ "$OSTYPE" == "darwin"* ]]; then
        MountOSXESP() {
    Temp=$(mount | sed -n -E "/^(\/dev\/disk[0-9]+s[0-9]+) on \/ \(.*$/s//\1/p")
    if [ $Temp ]; then
        Temp=$(diskutil list | grep " EFI " | grep -o 'disk.*' | head -n 1)
        if [ -z $Temp ]; then
            echo "Warning: root device doesn't have an EFI partition"
        fi
    else
        echo "Warning: root device could not be found"
    fi
    if [ -z $Temp ]; then
        Temp=$(diskutil list | sed -n -E '/^ *[0-9]+:[ ]+EFI EFI[ ]+[0-9.]+ [A-Z]+[ ]+(disk[0-9]+s[0-9]+)$/ { s//\1/p
                q
            }' )

        if [ -z $Temp ]; then
            echo "Could not find an EFI partition. Aborting!"
            exit 1
        fi
    fi
    Esp=/dev/`echo $Temp`
    echo "The ESP has been identified as $Esp; attempting to mount it...."
    Temp=`df -P | grep "$Esp "`
    MountPoint=`echo $Temp | cut -f 6- -d ' '`
    if [[ "$MountPoint" == '' ]] ; then
        if [[ $UID != 0 ]] ; then
            echo "You must run this program as root or using sudo! Exiting!"
            exit 1
        fi
        MountPoint="/Volumes/ESP"
        mkdir /Volumes/ESP &> /dev/null
        mount -t msdos "$Esp" $MountPoint
        if [[ $? != 0 ]] ; then
            mount -t hfs "$Esp" $MountPoint
            if [[ $? != 0 ]] ; then
                echo "Unable to mount ESP!\n"
                exit 1
            fi
        fi
    fi
    echo "The ESP is mounted at $MountPoint"
} MountOSXESP()
echo "include themes/refind-jbm/theme.conf" >> /Volumes/ESP/EFI/refind/refind.conf
sudo mkdir /Volumes/ESP/EFI/refind/themes/
sudo mkdir /Volumes/ESP/EFI/refind/themes/refind-jbm
wget https://github.com/jbmagination/refind-jbm/releases/download/1.0.0/refind-jbm.zip --directory-prefix=/Volumes/ESP/EFI/refind/themes/
unzip /Volumes/ESP/EFI/refind/themes/refind-jbm.zip
else
        echo Operating system type not found or not supported, exiting
        exit
fi;
